
.DATA_ID AMERICAN

.POINTS_PER_SECOND 70
.X_POINTS_PER_INCH 680
.Y_POINTS_PER_INCH 680

.DATA_INFO    
         Set type: 
         Alphabet: English keyboard alphanumerics and symbols 
                   from the ASCII set
         Lexicon: 
         Label distribution:
         Quantity:
         Quality: cleaned
         Number of Writer(s): 
         Writing Style: printed/cursive/mixed
         Segmentation: 

.PAD     Machine name: NEWTON
         Brand:APPLE
         Type:MP100
         Serial Nr.:
         Sensor:PRESSURE
         Pen:
         Driver:
         Sampling mode:EQUAL TIMED
         Sampling rate:70
         Resolution:680
         Accuracy:
         Width: 3in
         Height: 4in
         Display: Combined with tablet
         Inking: Present

.SETUP   Site: California  
         Time:  
         Writer population:
         Writer motivation: volunteer
         Writer physical position: sitting
         Instructions given to the writer: natural, neat
         Duration of one session:
         Recognizer feedback: yes/no
         Form layout:
